### ISSUE TITLE
不知道咋升级

### ISSUE THREAD

**Issue by BenBenJian** [ctaoist/leanote#1]
我用的是axboy的leanote，怎么升级你这个版本？
新手~挂载的位置没有你说的leanote/bin的文件夹

**Comment by ctaoist** [comment]
他用的应该是官方的包，参考 https://github.com/ctaoist/leanote/wiki/Leanote-install#%E4%BB%8E-26-%E5%8D%87%E7%BA%A7

**Comment by ctaoist** [comment]
他这种 docker 部署需要打包镜像的
