### ISSUE TITLE
起个文档，一直贴图片，就发现超过几张图后，就贴不上了，无法同步。

### ISSUE THREAD

**Issue by huangyy** [ctaoist/leanote#10]
服务端提示如下错误：
Resulting document after update is larger than 16777216
BSONObj size: 17056235 (0x10441EB) is invalid. Size must be between 0 and 16793600(16MB) First element: update: "note_contents"
没看到配置文件里面，有地方改这个东西，需要改源代码？

**Comment by ctaoist** [comment]
后台管理里面有个文件上传配置，你可是试试
