### ISSUE TITLE
前端二次开发npm依赖的工具链版本都是多少？

### ISSUE THREAD

**Issue by zhaotao1989** [ctaoist/leanote#13]
gulp版本比较低，安装最新的版本，gulp无法运行

**Comment by ctaoist** [comment]
nodejs要12以前的，比如11

**Comment by zhaotao1989** [comment]
知道了，我把这个package.json里面的依赖版本号补上了。

https://github.com/zhaotao1989/leanote/commit/aae3603e6f5f245bd2c5299fa312fd7de82f29fd

**Comment by zhaotao1989** [comment]
主要是那个笔记删除按钮我想加个确认弹窗，在开发模式下测试正常，但生产环境下好像没有生效。可能是在做发行包的时候没有gulp合并到app.js
