### ISSUE TITLE
markdown渲染不出来

### ISSUE THREAD

**Issue by wdluya** [ctaoist/leanote#14]
我用你修改过的2.7.6的版本。但是markdown渲染不出来。我使用官方的就没有问题。
<img width="1097" alt="WX20220815-192827@2x" src="https://user-images.githubusercontent.com/50042737/184628248-15da961b-c222-48fb-baef-e83831e8d699.png">
<img width="1090" alt="WX20220815-192849@2x" src="https://user-images.githubusercontent.com/50042737/184628256-585e5253-feb2-4dde-8980-7eeba44dc405.png">
<img width="1014" alt="WX20220815-193155@2x" src="https://user-images.githubusercontent.com/50042737/184628260-b9110108-3572-4872-bfc8-f13192f25e57.png">
<img width="973" alt="WX20220815-193210@2x" src="https://user-images.githubusercontent.com/50042737/184628263-d5e2034c-f685-4254-b250-1aa6c643c753.png">

**Comment by ctaoist** [comment]
打开开发者工具看看呢，可能是第三方库没有下载成功

**Comment by wdluya** [comment]
应该不是。看网络情况，应该就一个图片没有加载出来。
<img width="1273" alt="WX20220816-102700@2x" src="https://user-images.githubusercontent.com/50042737/184785865-755a1ac5-bf2f-414e-8aa5-701a21174dec.png">
<img width="1277" alt="WX20220816-102842@2x" src="https://user-images.githubusercontent.com/50042737/184785869-779eeda3-1d14-476b-b987-d52404f07bbd.png">
<img width="1266" alt="WX20220816-102935@2x" src="https://user-images.githubusercontent.com/50042737/184785873-c210b46e-90ad-4e17-ab75-f297f7b034c0.png">

**Comment by ctaoist** [comment]
看情况是你只替换了二进制文件？问题是js的一些函数没有找到

**Comment by wdluya** [comment]
> 看情况是你只替换了二进制文件？问题是js的一些函数没有找到
二进制和数据库我的替换了。浏览器缓存的问题。我把浏览器的缓存清了一下就渲染出来。谢谢您的回复。
