### ISSUE TITLE
网站域名一经设置，使用一段时间后，就无法再进行修改

### ISSUE THREAD

**Issue by wiselike** [ctaoist/leanote#16]
目前遇到的这个问题，感觉比较严重，详情请见https://github.com/wiselike/leanote-of-unofficial/issues/2 ,想找你讨论一下，有啥好的解决办法没？

**Comment by ctaoist** [comment]
插入的图片默认不是全链接吧，相对链接没有这个问题啊，我记得一般是 `/api/file/getImage?fileId=625fdd6b421a` 类似这种形式，全链接是你自己做的修改？我这边没做任何修改默认就是相对链接形式

**Comment by wiselike** [comment]
从别的网页复制过来的图片，会自动转换为本地链接，这时在笔记中就是全链接的。我这边看到的就是这样。

**Comment by wiselike** [comment]
此故障已修复，MR详见：https://github.com/wiselike/leanote-of-unofficial/pull/3

**Comment by ctaoist** [comment]
你的 `tiny/node_modules` 这个文件夹竟然也纳入版本管理。。。。。
