### ISSUE TITLE
还是你的名字

### ISSUE THREAD

**Issue by doumeki** [ctaoist/leanote#2]
![image](https://user-images.githubusercontent.com/10527841/148777740-fb07f35e-e6fa-4c77-9ed9-c8d7877556e0.png)

**Comment by ctaoist** [comment]
你这个是主题的配置文件没修改吧，`PostAuthor` 这个。

ps. 如果是主题相关的问题，请到 https://github.com/ctaoist/leanote-theme-chirpy 这个仓库下发 issue
