### ISSUE TITLE
请问一下，网站cdn是怎么配置的？

### ISSUE THREAD

**Issue by wiselike** [ctaoist/leanote#3]
您好，我最近才开始研究leanote，也在研究你的网站和补丁。

请问一下，https://blog.ctaoist.cn/的cdn是怎么配置的，好像并没有合入到这个项目里。
图片的加载url也跟原生的有所不同。

**Comment by ctaoist** [comment]
能具体说说？

ps. 如果是主题相关的问题，请到 https://github.com/ctaoist/leanote-theme-chirpy 这个仓库发 Issue

**Comment by wiselike** [comment]
例如页面：https://blog.ctaoist.cn/blog/post/ctaoist/Mathematica%E6%A8%A1%E6%8B%9F%E6%BB%91%E5%9D%97%E6%91%86%E8%BF%90%E5%8A%A8
里面有两张图片：
1. http://blog.qiniu.ctaoist.cn/%E6%BB%91%E5%9D%97%E6%91%86%E7%A4%BA%E6%84%8F%E5%9B%BE.png
2. 
http://blog.qiniu.ctaoist.cn/%E6%BB%91%E5%9D%97%E6%91%86%E7%9A%84%E8%BF%90%E5%8A%A8%E5%8A%A8%E7%94%BB.gif

它这里的url域都是blog.qiniu.ctaoist.cn，都用了qiniu的cdn加速。
按默认的话应该是blog.ctaoist.cn才对，请问，这里的图片URL怎么配置，可以变成blog.qiniu.ctaoist.cn？

**Comment by ctaoist** [comment]
这个是我自己上传到七牛云的，不是自动完成的，以后看情况能不能集成，你要是能够pr更好

**Comment by wiselike** [comment]
> 这个是我自己上传到七牛云的，不是自动完成的

一张一张图片改url地址啊，把域改成qiniu的，那确实比较麻烦的

**Comment by ctaoist** [comment]
写的时候就上传到七牛云啊，不是后期一起改的

**Comment by ctaoist** [comment]
添加了七牛云图床支持，你要是有兴趣，可以添加新的图床

![blog_cloud_0](https://user-images.githubusercontent.com/14012127/163758406-1ce4b90d-46a8-4803-b552-21454c2484ad.png)

**Comment by wiselike** [comment]
你的补丁不全吧，`configService.GetGlobalMapConfig("Cloud_Qiniu")`只看到有使用的地方，没有看到有定义的地方

**Comment by ctaoist** [comment]
存数据库里面的
