### ISSUE TITLE
请问怎么设置博文置顶？

### ISSUE THREAD

**Issue by wiselike** [ctaoist/leanote#4]
请问怎么设置博文置顶呢，没有看到设置方法？

**Comment by ctaoist** [comment]
现在前端还没有做置顶的接口，想置顶可以手动改数据库，`Notes` 表下对应笔记的 `IsTop` 字段改成 true 就可以了

**Comment by wiselike** [comment]
> 现在前端还没有做置顶的接口

请问有安排不？:)

**Comment by ctaoist** [comment]
有这个计划，但前端代码看的头疼，估计要比较久了
