### ISSUE TITLE
问一下，2.7.6版本运行时，出现如下错误，是什么原因？Linux版本是Ubuntu 20.04

### ISSUE THREAD

**Issue by huangyy** [ctaoist/leanote#9]
DEBUG 17:38:51  revel server.go:123: InitServerEngine: Found server engine and invoking  section=server name=go 
INFO  17:38:51  revel   event.go:46: Raising event                              section=util len=5
INFO  17:38:51  revel revel_logger.go:29: There is 12 hooks need to run ...          section=server
INFO  17:38:51  revel revel_logger.go:29: Run the 1 hook ...                        section=util 
panic: no reachable servers [recovered]
	panic: Fatal error in startup

goroutine 1 [running]:
github.com/revel/revel.Run.func1()
	/home/runner/go/pkg/mod/github.com/revel/revel@v1.0.0/server.go:70 +0xcf
panic({0xab0a00, 0xc000334620})
	/opt/hostedtoolcache/go/1.18.1/x64/src/runtime/panic.go:838 +0x207
github.com/leanote/leanote/app/db.Init({0x0?, 0x0?}, {0x0?, 0x0?})
	/home/runner/work/leanote/leanote/app/db/Mgo.go:109 +0x2d3f
github.com/leanote/leanote/app.init.0.func28()
	/home/runner/work/leanote/leanote/app/init.go:423 +0x27
github.com/revel/revel.RevelHooks.Run({0xc0000f0600, 0xc, 0x10})
	/home/runner/go/pkg/mod/github.com/revel/revel@v1.0.0/revel_hooks.go:32 +0x18a
github.com/revel/revel.InitServer()
	/home/runner/go/pkg/mod/github.com/revel/revel@v1.0.0/server.go:39 +0x52
github.com/revel/revel.Run(0xb7e05d?)
	/home/runner/go/pkg/mod/github.com/revel/revel@v1.0.0/server.go:81 +0x118
github.com/leanote/leanote/app/tmp/run.Run(0x0?)
	/home/runner/work/leanote/leanote/app/tmp/run/run.go:36 +0x28
main.main()
	/home/runner/work/leanote/leanote/app/tmp/main.go:24 +0x98

**Comment by ctaoist** [comment]
感觉是数据库密码之类的错了，没连接上数据库

**Comment by huangyy** [comment]
果然，是数据库密码没改过来。。。
